### ISSUE TITLE
getCameraBitmap() null

### ISSUE THREAD

**Issue by c2digital** [janishar/ParaCamera#13]
The following:-

```
@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        if (requestCode == Camera.REQUEST_TAKE_PHOTO) {

            Bitmap bm = camera.getCameraBitmap(); // <-- Causes null exception

           }
    }
```

Results in the following error:-

`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Bitmap com.mindorks.paracamera.Camera.getCameraBitmap()' on a null object reference`

Library: com.mindorks:paracamera:0.2.2
API: 23

Note: Image is displayed in gallery. getCameraBitmapPath() *does* return a valid file path

**Comment by janishar** [comment]
@caphson 

Have you build the camera and retained the reference in the global class variable?
